Feat/penalty
Normal-OJ/Back-End pull request #173
Opened 2022-11-23 14:08 UTC by 180079995

2022-11-23 16:42 UTC, Bogay requested changes
雖然目前有做白名單，但我建議 `exec` 可以改成 `eval`，後者只可以接受單一 expression 因此更嚴格，並且也足以滿足我們的需求了（回傳分數）。

2022-11-23 16:42 UTC, Bogay commented on mongo/submission.py
> +            if self.timestamp > homework.duration.end and not self.handwritten and homework.penalty is not None:
這個檢查是多餘的，上面已經做過了。
```suggestion
            if self.timestamp > homework.duration.end and homework.penalty is not None:
```

2022-11-23 16:42 UTC, Bogay commented on model/homework.py
> +            homework.penalty if hasattr(homework, 'penalty') else None,
`homework.penalty` 應該都會存在，可以不用檢查？
```suggestion
            homework.penalty
```

2022-11-23 16:42 UTC, Bogay commented on mongo/homework.py
> +            d['score'] = int(d['score'])
這邊轉型有可能會失敗？

2022-11-23 16:42 UTC, Bogay commented on tests/unittest/submission/test_penalty.py
> +    problem_ids: List[int] = [],
function 的預設參數不建議放物件進去，因為在所有的 function call 裡面會共用這個預設值（絕大多數情況下不是預期行為），所以改成預設為 `None` 然後在 function 執行的時候才 assign 會比較好。

2022-11-23 16:42 UTC, Bogay commented on tests/unittest/submission/test_penalty.py
> +    problem_ids: List[int] = [],
底下也有相同狀況需要一併修改。

2022-12-03 14:31 UTC, 180079995 commented on mongo/homework.py
> +            raise ValueError("Invalid penalty")
Illegal 是表達式中有不允許的內容
Invalid 是表達式無法執行

2022-12-03 14:33 UTC, 180079995 commented on mongo/homework.py
> +def check_penalty(penalty):
我覺得錯誤訊息不需要另存一個值吧，我把它放在homework.py的頂部好了。

2022-12-03 14:34 UTC, 180079995 commented on mongo/engine.py
> +    penalty = StringField(max_length=10000, default='')
我預設值改成 'score = 0'
讓他預設是遲交0分

2022-12-03 14:35 UTC, 180079995 commented on model/homework.py
> +            homework.penalty if hasattr(homework, 'penalty') else None,
我主要是怕已經存在的作業會沒有penalty這項值，所以做個檢查

2022-12-03 14:37 UTC, 180079995 commented on mongo/homework.py
> +            d['score'] = int(d['score'])
什麼轉型失敗?
要轉型是怕它們有可能變成float

2022-12-03 14:46 UTC, 180079995 commented on tests/unittest/submission/test_penalty.py
> +    )
我發現add_problem 好像有點問題，先刪掉了
add_homework移到 test/utils/homework.py 了

2022-12-07 11:51 UTC, 180079995 commented
> 雖然目前有做白名單，但我建議 `exec` 可以改成 `eval`，後者只可以接受單一 expression 因此更嚴格，並且也足以滿足我們的需求了（回傳分數）。

2022-12-07 11:53 UTC, 180079995 commented
> 雖然目前有做白名單，但我建議 `exec` 可以改成 `eval`，後者只可以接受單一 expression 因此更嚴格，並且也足以滿足我們的需求了（回傳分數）。

用exec是希望如果想用for的話可以用，不然的話eval比較方便。

2022-12-07 14:28 UTC, Bogay reviewed
目前的變更看過了，不過是否有一些 commit 沒有被 push 上來？
另外因為我把 github actions 修正完了，我會傾向先把那邊 merge 進去後你再把更新過的 workflow merge 進來。

2022-12-07 14:28 UTC, Bogay commented on model/homework.py
> +            homework.penalty if hasattr(homework, 'penalty') else None,
因為有指定預設值，所以若 DB 內沒有存的話，就會取預設值，我想都會存在？

2022-12-07 14:28 UTC, Bogay commented on mongo/homework.py
> +            raise ValueError("Invalid penalty")
瞭解，那我認為你可以把錯誤訊息寫得更詳細一點，讓接到錯誤的人更清楚原因。

2022-12-14 15:25 UTC, Bogay approved these changes

2022-12-14 15:25 UTC, merged