Feat auto open problem
Normal-OJ/Back-End pull request #272
Opened 2023-06-28 04:10 UTC by ra890927

#166

2023-06-28 15:30 UTC, Bogay requested changes
Thanks，把 `perm` 移掉感覺好多了，留了些建議再幫我看看

2023-06-28 15:30 UTC, Bogay commented on mongo/problem/problem.py
> +            else:
這邊應該不需要針對 public 特別做檢查？他的權限沒有特例

2023-06-28 15:30 UTC, Bogay commented on tests/test_get_homewrok_problem.py
> +        assert len(rv_data) == 1
不確定我是不是誤會了，但作業開始前同學要看不到題目？

2023-06-28 15:30 UTC, Bogay commented on tests/test_get_homewrok_problem.py
> +        )
感覺直接 patch `datetime.now` 會讓這段比較好看？不然寫這 10 行只是為了最後兩行的更新 duration

2023-06-28 15:30 UTC, Bogay commented on model/submission.py
> +            return HTTPError('you have used all your quotas', 403)
這邊多拆幾行應該可讀性會好點

```suggestion
    if problem.obj.quota != -1:
        no_grade_permission = not any(
            c.permission(user=user, req=Course.Permission.GRADE)
            for c in map(Course, problem.courses))
        run_out_of_quota = problem.submit_count(user) >= problem.quota
        if no_grade_permission and run_out_of_quota:
            return HTTPError('you have used all your quotas', 403)
```

2023-06-28 16:08 UTC, ra890927 commented on mongo/problem/problem.py
> +            else:
這邊是按照原本的寫法修改的，沒有的話我就拔掉了

2023-06-28 16:08 UTC, ra890927 commented on tests/test_get_homewrok_problem.py
> +        assert len(rv_data) == 1
難道不是嗎?

2023-06-28 16:11 UTC, ra890927 commented on tests/test_get_homewrok_problem.py
> +        )
這邊算是遇到一個比較難解決的問題，因為 datetime.now 是 built-in function 無法直接 patch，但是 patch datetime 的話在建立 Flask 會使用到 datetime 的其他 function，所以我只好用這種方法去做時間上的修改

2023-06-30 17:46 UTC, Bogay commented on tests/test_get_homewrok_problem.py
> +        )
看到[這篇](https://stackoverflow.com/a/25652721)，在我本機測試過會動，大概會像這樣：

```python
        from unittest.mock import patch

        with patch('mongo.problem.problem.datetime') as mock_datetime:
            mock_datetime.now.return_value = datetime.now() - timedelta(days=21)

            client = forge_client('Bo-Chieh-Chuang')
            rv, rv_json, rv_data = self.request(
                client, 'get', f'/problem/2?course={course_data.name}')

        print(rv_json)

        assert rv.status_code == 403
        assert rv_json['status'] == 'err'
        assert rv_json['message'] == 'Problem is unavailable'
```

2023-06-30 17:46 UTC, Bogay commented on tests/test_get_homewrok_problem.py
> +        assert len(rv_data) == 1
噢，我看懂了，這邊 `rv_data` 裡面的是 Public 底下那題？
看來這邊可以考慮改一下 assert 的條件，我覺得檢查題目列表中不存在作業題目 && 直接存取作業題目會失敗比較合理。

2023-06-30 17:46 UTC, Bogay commented on mongo/problem/problem.py
> +            else:
嗯...雖然我覺得自己應該沒記錯，但還是請 @as535364 @uier 也確認一下？我嘗試把這邊檢查拔掉後測試是有通過。

2023-07-01 15:29 UTC, ra890927 commented on tests/test_get_homewrok_problem.py
> +        assert len(rv_data) == 1
我不確定有沒有誤會，我是寫成如果這堂課裡面的題目不屬於任何一個作業的話，他就是這堂課的公開題目
如果要 assert 那些條件的話，要改成手動去新增題目，現在是用亂數生的

2023-07-01 15:48 UTC, Bogay commented on tests/test_get_homewrok_problem.py
> +        assert len(rv_data) == 1
不用吧？用類似這樣的 statement 應該就行：`assert all(p['problemId'] not in ... for p in rv_data)`

2023-07-20 14:36 UTC, Bogay approved these changes
👍

2023-07-20 14:36 UTC, merged